name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - run: docker build -t bingisainath/docker-react -f Dockerfile.dev .
      
      # Run tests inside the container
      - run: docker run -e CI=true bingisainath/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.get*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-600627316973 
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip


# http://frontend-env.eba-pmbpbxaq.eu-north-1.elasticbeanstalk.com/
# elasticbeanstalk-ap-south-1-600627316973
# gBMqbcYYJH9kKlRqkHEpMrPGsYupE3Eqe6XjGH/o